version: '3.8'

services:
  junior-assistant:
    build: .
    container_name: junior-assistant
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - EVOLUTION_API_URL=${EVOLUTION_API_URL}
      - EVOLUTION_API_KEY=${EVOLUTION_API_KEY}
      - EVOLUTION_INSTANCE=${EVOLUTION_INSTANCE}
    volumes:
      - ./data:/app/data
      - ./knowledge_base:/app/knowledge_base
    networks:
      - junior-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:alpine
    container_name: junior-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl  # Para certificados SSL (opcional)
    depends_on:
      - junior-assistant
    networks:
      - junior-network

networks:
  junior-network:
    driver: bridge

volumes:
  junior-data:
    driver: local